### ISSUE TITLE
Function which returns segmentation

### ISSUE THREAD

**Issue by clbarnes** [smups/rustronomy-watershed#1]
If I'm reading the docs right, the `Watershed::transform` returns information about the size of lakes. Is there, or could there be, a function which actually returns the segmented image (probably for a given water level)?

**Comment by smups** [comment]
Yep that's right, that's all it does rn.

Returning the final segmented (or in the case of the merging transform, completely merged) image could be implemented trivially.

I might as well do that, sounds like that'd be much more useful than just the lake sizes for most people. API isn't stable anyway.

Getting the segmented image for each water level is possible too by cloning the intermediate segmented image every time the water level is raised. That would come at a significant performance penalty though (allocating a big image each time the water level is raised).

Both of these are quick additions, I'll add them.

**Comment by clbarnes** [comment]
Maybe something like an iterator which would own the watershed-er and return a new image at each increment of the water level, for people who needed that despite the penalty? And otherwise, just a function which takes the desired level, and/or an enum of level or "until there are no unsegmented pixels"?

**Comment by smups** [comment]
I've added two new methods in `v0.2`! One just returns the transform, the other a Vec of images at each water level.

That iterator idea sounds very cool too, I'll look into that if I have time.

You can set the max water level for the transform with the `TransformBuilder` btw.
