### ISSUE TITLE
Edge pixel handling

### ISSUE THREAD

**Issue by clbarnes** [smups/rustronomy-watershed#2]
Would it be possible to get access to those border pixels by extending the image using something like [numpy's `pad`](https://numpy.org/doc/stable/reference/generated/numpy.pad.html)? It looks like there are a couple of implementations (from the [ndarray issue](https://github.com/rust-ndarray/ndarray/issues/823)):

- https://github.com/imeka/ndarray-ndimage (more fully-featured)
- https://github.com/imjasonmiller/ndarray-pad (more focused)

This would obviously be an extra copy, so maybe it would be best to keep the existing functionality as-is and just re-export a blessed implementation with whatever type shims are necessary, for people who need that pixel border.

This would be particularly useful for segmentations of very large images split into tiles.

**Comment by smups** [comment]
Thanks for the input! I'll be merging a PR soonish that adds a workaround based on the method you described. It can be enabled by calling the `enable_edge_correction` function on the transform builder.
